# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder '..', '/dropcaster'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '256'
  end

  %w(1.9.1 2.0 2.1 2.2).each do |version|
    ruby = "ruby#{version}"
    name = "ruby-#{version.tr('.', '-')}"

    config.vm.define(name) do |cfg|
      cfg.vm.hostname =
      cfg.vm.provision 'shell', inline: <<-SHELL
        sudo apt-get install software-properties-common
        sudo add-apt-repository ppa:brightbox/ruby-ng
        sudo apt-get update
        sudo apt-get install -y git libxml2-dev zlib1g-dev #{ruby} #{ruby}-dev

        sudo su -c 'echo "LC_ALL=en_US.UTF-8" >> /etc/environment'

        sudo gem install bundler
        cd /dropcaster
        bundle
        bundle exec rake
      SHELL
    end
  end
end
