AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

  NewCops: enable

Naming/FileName:
  Exclude:
  - Guardfile
  - Vagrantfile
  - test/Vagrantfile
  - Dockerfile

Metrics/BlockLength:
  Exclude:
    - test/**/*

Layout/LineLength:
  Max: 180
  Exclude:
    - test/**/*
