# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dropcaster}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{nerab}]
  s.date = %q{2011-10-03}
  s.description = %q{Dropcaster is a podcast feed generator for the command line. It is most simple to use with Dropbox, but works equally well with any other hoster.}
  s.email = %q{nerab@gmx.at}
  s.executables = [%q{lstags}, %q{dropcaster}, %q{dropcaster}, %q{lstags}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/dropcaster",
    "bin/lstags",
    "lib/dropcaster.rb",
    "lib/dropcaster/channel.rb",
    "lib/dropcaster/errors.rb",
    "lib/dropcaster/hashkeys.rb",
    "lib/dropcaster/item.rb",
    "templates/channel.rss.erb",
    "test/fixtures/iTunes.mp3",
    "test/fixtures/infoPane.png",
    "test/fixtures/lyricsPane.png",
    "test/fixtures/test_channel.yml",
    "test/fixtures/videoPane.png",
    "test/helper.rb",
    "test/unit/test_channel.rb",
    "test/unit/test_item.rb"
  ]
  s.homepage = %q{http://github.com/nerab/dropcaster}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{Simple Podcast Publishing with Dropbox}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-mp3info>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<libxml-ruby>, [">= 0"])
    else
      s.add_dependency(%q<ruby-mp3info>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-mp3info>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
  end
end

