# Site settings
title: Dropcaster
email: nerab@gmx.at
description: > # this means to ignore newlines until "baseurl:"
  Dropcaster is a podcast feed generator for the command line. It  works with any (static file) web hoster.
baseurl: "/dropcaster" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  nerab

# Build settings
markdown: kramdown
